[package]
name = "pantryman-bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cookbook-engine = { path = "../../cookbook-engine" }
jni = "0.21"
serde_json = "1.0"
chrono = "0.4"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13"
log = "0.4"
