[package]
name = "cookbook-engine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
quick-xml = "0.37.5"
log = "0.4"
chrono = "0.4.41"
android_logger = "0.14"
